import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { EventProvider } from "@/context/EventContext";
import { ThemeProvider } from "@/context/ThemeContext";
import Navbar from "./components/Navbar";

const manrope = Manrope({
  variable: "--font-manrope",
  display: "swap",
  preload: true,
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Loumatix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("font-manrope", manrope.variable)}>
        <ThemeProvider>
          <EventProvider>
            <Navbar />
            {children}
          </EventProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
